Repository viniciuslft/e-commerce-tech, pull requests merged in 2024-11, with the labels that each got.

#2 add: novos layouts
  index.css
  index.html
  sass/style.scss
  static/assets/img/carousel/carousel1.svg
  static/assets/img/carousel/carousel2.svg
  static/assets/img/carousel/carousel3.svg
  static/assets/img/cart.svg
  static/assets/img/favorite.svg
  static/assets/img/logoFundo.png
  static/assets/img/logoFundoajustado.png
  static/assets/img/produtos/emptyProduct.png
  static/assets/img/produtos/headset.png
  static/assets/img/user.svg
  static/css/style.css
  static/css/style.css.map
  static/js/script.js
  style.css
  templates/favoriteList.html
  templates/forgotpass.html
  templates/index.html
  templates/login.html
  templates/productInfo.html
  templates/signup.html
  templates/successSignup.html
Labels: bug, documentation, enhancement

#3 add: started backend
  app.py
Labels: documentation, enhancement

#4 Irineu
  app.py
  templates/index.html
  templates/login.html
  templates/signup.html
Labels: enhancement
